version: '3'
services:
  website:
    image: "php:8.1-apache"
    volumes:
      - ./src:/var/www/html
      - ./apache2.conf:/etc/apache2/apache2.conf
    container_name: "portfolio"
    ports:
      - "8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.localhost`)"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=staging" # TODO: change in production to production
