# Use an official Node.js image with npm
FROM node:18-alpine

# Set the working directory
WORKDIR /src

# Copy only package.json and package-lock.json initially to leverage Docker caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the port Next.js is running on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]
