apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-deployment
  template:
    metadata:
      labels:
        app: portfolio-deployment
    spec:
      containers:
        - name: portfolio
          image: rutger505/portfolio:1.1.1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: portfolio-config
            - secretRef:
                name: portfolio-secret
