apiVersion: v1
kind: Service
metadata:
  name: rutgerpronk-nextjs-service
spec:
  selector:
    app: rutgerpronk-nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
