name: Deploy to Kubernetes

on:
  push:
    branches:
      - migrate-to-k8s

jobs:
  deploy:
    uses: rutger505/deploy-to-kubernetes/.github/workflows/deploy.yaml@fix-environment-variables-with-spaces
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}

      image_name: rutger505/portfolio:${{ github.ref_name }}

      deployment_name: portfolio-deployment

      configmap_name: portfolio-config
      configmap_literals: GMAIL_USER=rutger.pronk19@gmail.com,RECIPIENT_EMAIL=rutger.pronk11@gmail.com,TEST_WITH_SPACES_AND_SINGLE_QUOTES='This is a test'

      secret_name: portfolio-secret

      kubernetes_files_replace_literals: "TAG_NAME=${{ github.ref_name }}"
    secrets:
      kube_config: ${{ secrets.KUBECONFIG }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      secret_literals: GMAIL_APP_PASSWORD='${{ secrets.GMAIL_APP_PASSWORD }}'
