name: Call Deploy Workflow

on:
  release:
    types: [published]

jobs:
  deploy:
    uses: rutger505/deploy-to-kubernetes/.github/workflows/deploy.yaml@add-deploy-file
    with:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      image_name: rutger505/portfolio:${{ github.event.release.tag_name }}
      deployment_name: portfolio-deployment
      configmap_name: portfolio-config
      configmap_literals: "GMAIL_USER=rutger.pronk19@gmail.com,RECIPIENT_EMAIL=rutger.pronk11@gmail.com"
      secret_name: portfolio-secret
      secret_literals: "GMAIL_APP_PASSWORD='ngrk bgzi iebw veat'"
