name: Call Deploy Workflow

#on:
#  release:
#    types: [published]

on:
  push:
    branches:
      - migrate-to-k8s

jobs:
  deploy:
    uses: rutger505/deploy-to-kubernetes/.github/workflows/deploy.yaml@add-deploy-file
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
#      image_name: rutger505/portfolio:${{ github.ref_name }}
      image_name: rutger505/portfolio:1.1.2
      deployment_name: portfolio-deployment
      configmap_name: portfolio-config
      configmap_literals: "GMAIL_USER=rutger.pronk19@gmail.com,RECIPIENT_EMAIL=rutger.pronk11@gmail.com"
      secret_name: portfolio-secret
    secrets:
      kube_config: ${{ secrets.KUBECONFIG }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      secret_literals: GMAIL_APP_PASSWORD='{{ secrets.GMAIL_APP_PASSWORD }}'
