name: Deploy

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Define tag name
        run: |
          if [[ ${{ github.ref }} == 'refs/tags/'* ]]; then
            TAG_NAME=${{ github.ref_name }}
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          else
            TAG_NAME=${{ github.sha }}
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          fi
          echo "Setting TAG_NAME to $TAG_NAME"

      - uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rutger505/portfolio:${{ env.TAG_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs:
      - build-docker-image

    steps:
      - name: Define tag name
        run: |
          if [ "$GITHUB_REF" = "refs/tags/*" ]; then
            TAG_NAME=$GITHUB_REF_NAME
          else
            TAG_NAME=$GITHUB_SHA
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "Setting TAG_NAME to $TAG_NAME"

      - name: Define environment
        run: |
          if [ "$GITHUB_REF" = "refs/tags/*" ]; then
            ENVIRONMENT=production
          else
            ENVIRONMENT=pull-request-${{ github.event.number }}
          fi
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "Setting ENVIRONMENT to $ENVIRONMENT"

      - name: Define namespace
        run: |
          echo "NAMESPACE=portfolio-$ENVIRONMENT" >> $GITHUB_ENV
          echo "Setting NAMESPACE to portfolio-$ENVIRONMENT"

      - name: Define ingress host
        run: |
          if [ "$ENVIRONMENT" = "production" ]; then
            INGRESS_HOST=rutgerpronk.com
          else
            INGRESS_HOST=$GITHUB_SHA.rutgerpronk.com
          fi
          echo "INGRESS_HOST=$INGRESS_HOST" >> $GITHUB_ENV
          echo "Setting INGRESS_HOST to $INGRESS_HOST"

      - uses: actions/checkout@v4

      - name: Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext-base

      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v4.0.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Insert environment variables into Kubernetes files
        run: |
          FILES=$(ls k8s/*.yaml | tr '\n' ' ')
          
          for FILE in $FILES; do
            echo "Processing $FILE"
            envsubst < $FILE > /tmp/envsubst || exit 1
            mv /tmp/envsubst $FILE || exit 1
          done
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
          INGRESS_HOST: ${{ env.INGRESS_HOST }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

      - name: Create namespace if not exists
        run: |
          if ! kubectl get namespace $NAMESPACE &> /dev/null; then
            echo "Namespace $NAMESPACE does not exist, creating it"
            kubectl create namespace $NAMESPACE
          else
            echo "Namespace $NAMESPACE already exists"
          fi

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          namespace: ${{ env.NAMESPACE }}
          manifests: |
            k8s/

      - name: Comment deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const url = `https://${{ env.INGRESS_HOST }}`;
            const message = `🚀 Preview deployment is available at: ${url}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: message
            });