name: Deploy to Kubernetes

on:
  push:
    tags:
      - '*'
jobs:
  Build Docker image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t rutger505/portfolio:${{ github.ref_name  }} .
        docker push rutger505/portfolio:${{ github.ref_name }}

  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.30.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/portfolio portfolio=rutger505/portfolio:${{ github.ref_name }}
        kubectl rollout status deployment/portfolio

    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
