name: Deploy to Kubernetes

on:
  release:
    types:
      - created

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        TAG_NAME=${{ github.event.release.tag_name }}
        docker build -t rutger505/portfolio:${TAG_NAME} .
        docker push rutger505/portfolio:${TAG_NAME}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Kubernetes
    needs: build-docker-image
    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.30.0'

    - name: Setup yq
      uses: mikefarah/yq@v4.44.3

    - name: Deploy to Kubernetes
      run: |
        TAG_NAME=${{ github.event.release.tag_name }}
        DEPLOYMENT_NAME=$(yq '.metadata.name' k8s/deployment.yaml --unwrapScalar)
        
        envsubst < k8s/deployment.yaml | kubectl replace -f -
        envsubst < k8s/service.yaml | kubectl replace -f -
        envsubst < k8s/ingress.yaml | kubectl replace -f -
        
        
        kubectl rollout restart deployment/${DEPLOYMENT_NAME}
