name: Deploy to Kubernetes

on:
  release:
    types:
      - created

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t rutger505/portfolio:${{ github.event.pull_request.head.ref  }} .
        docker push rutger505/portfolio:${{ github.event.pull_request.head.ref }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-image
    name: Deploy to Kubernetes

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.30.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/

    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
